---

version: 2.0

workflows:
  version: 2
  build:
    jobs:
      - pep8
      - py27:
          requires:
            - pep8
      - py37:
          requires:
            - pep8
      - docs:
          requires:
            - pep8
  periodic:
    triggers:
      - schedule:
          cron: "0 0 1 * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - pep8
      - py27:
          requires:
            - pep8
      - py37:
          requires:
            - pep8

jobs:
  pep8: &test-template
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            virtualenv venv
            ./venv/bin/pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}
      - run:
          name: Run tests
          command: ./venv/bin/tox -e ${CIRCLE_STAGE}

  py27:
    <<: *test-template
    docker:
      - image: circleci/python:2.7

  py37:
    <<: *test-template
    docker:
      - image: circleci/python:3.7

  docs:
    <<: *test-template
    docker:
      - image: circleci/python:3.7
