---

version: 2.0

workflows:
  version: 2
  lint:
    jobs:
      - pep8
  test:
    jobs:
      - py27
      - py34
      - py35
      - py36
      - py37
  docs:
    jobs:
      - docs

jobs:
  py27: &test-template
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            virtualenv venv
            ./venv/bin/pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}
      - run:
          name: Run tests
          command: ./venv/bin/tox -e ${CIRCLE_STAGE}

  py34:
    <<: *test-template
    docker:
      - image: circleci/python:3.4

  py35:
    <<: *test-template
    docker:
      - image: circleci/python:3.5

  py36:
    <<: *test-template
    docker:
      - image: circleci/python:3.6

  py37:
    <<: *test-template
    docker:
      - image: circleci/python:3.7

  pep8:
    <<: *test-template
    docker:
      - image: circleci/python:3.7

  docs:
    <<: *test-template
    docker:
      - image: circleci/python:3.7
