---

version: 2.0

workflows:
  version: 2
  build:
    jobs:
      - lint
      - py27:
          requires:
            - lint
      - py37:
          requires:
            - lint
      - docs:
          requires:
            - lint
  deploy:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^v[0-9]+([.0-9]+)*/
            branches:
              ignore: /.*/
  periodic:
    triggers:
      - schedule:
          cron: "0 0 1 * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - lint
      - py27:
          requires:
            - lint
      - py37:
          requires:
            - lint

jobs:
  base: &test-template
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Revision }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            virtualenv venv
            ./venv/bin/pip install -r requirements.txt
      - run:
          name: Run tests
          command: ./venv/bin/tox -e ${CIRCLE_STAGE}
      - save_cache:
          key: v1-dependencies-{{ .Revision }}
          paths:
            - ./venv
            - ./.tox

  lint:
    <<: *test-template

  py27:
    <<: *test-template
    docker:
      - image: circleci/python:2.7

  py37:
    <<: *test-template

  docs:
    <<: *test-template

  deploy:
    <<: *test-template
