name: pick-files
base: core22
adopt-info: pick-files-go

summary: A script that picks a random selection of files
description: |
  A script that copies a random selection of files from a set of folders to a
  single destination folder.
icon: icon-256.png
license: Apache-2.0
website: https://github.com/nicolasbock/filechooser

grade: stable
confinement: strict

apps:
  pick-files:
    command: usr/bin/pick-files
    plugs:
      - home
      - removable-media
  pick-files-go:
    command: usr/bin/pick-files-go
    plugs:
      - home
      - removable-media

parts:
  pick-files-go:
    plugin: dump
    source: .
    build-snaps:
      - go
    override-build: |
      set -e -u -x
      VERSION=$(git describe --tags)
      craftctl set version=${VERSION}
      go build -ldflags "-X main.Version=${VERSION}" -o pick-files ./...
      install --mode 0755 -D pick-files ${CRAFT_PART_INSTALL}/usr/bin/pick-files-go

  pick-files-python:
    plugin: python
    source: .
    python-requirements:
      - requirements.txt
    organize:
      bin/pick-files: usr/bin/pick-files
