name: pick-files
base: core22
adopt-info: pick-files

summary: A script that picks a random selection of files
description: |
  `pick-files` is a script that randomly selects a specific number of files
  from a set of folders and copies these files to a single destination folder.
  During repeat runs the previously selected files are excluded from the
  selection for a specific time period that can be specified.

  Usage Example
  -------------

      pick-files --number 20 \
          --destination output \
          --suffix .jpg --suffix .avi \
          --folder folder1 --folder folder2

  Would choose at random 20 files from `folder1` and `folder2` (including
  sub-folders) and copy those files into `output`. The `output` is created if
  it does not exist already. In this example, only files with suffixes `.jpg`
  or `.avi` are considered.

icon: icon/icon-256.svg
license: Apache-2.0
source-code: https://github.com/nicolasbock/filechooser
website: https://filechooser.readthedocs.io/

grade: stable
confinement: strict

apps:
  pick-files:
    command: usr/bin/pick-files
    completer: usr/share/pick-files/pick-files-bash-completions.sh
    plugs:
      - home
      - removable-media
  pick-files-daily:
    command: /usr/bin/pick-files
    daemon: simple
    timer: 09:00
    plugs:
      - home
      - removable-media
  autorotate:
    command: usr/bin/autorotate.sh
    completer: usr/share/pick-files/autorotate-bash-completions.sh
    plugs:
      - home
      - removable-media

parts:
  pick-files:
    plugin: dump
    source: .
    build-snaps:
      - go
    override-build: |
      set -e -u -x
      VERSION=$(git describe --tags)
      craftctl set version=${VERSION}
      make
      install --mode 0755 -D pick-files ${CRAFT_PART_INSTALL}/usr/bin/pick-files
      install --mode 0755 -D scripts/autorotate.sh ${CRAFT_PART_INSTALL}/usr/bin/autorotate.sh
      install --mode 0755 -D scripts/pick-files-bash-completions.sh ${CRAFT_PART_INSTALL}/usr/share/pick-files/pick-files-bash-completions.sh
      install --mode 0755 -D scripts/pick-files-bash-completions.sh ${CRAFT_PART_INSTALL}/usr/share/pick-files/autorotate-bash-completions.sh
      install --mode 0644 -D docs/source/tips-and-tricks.rst ${CRAFT_PART_INSTALL}/usr/share/doc/pick-files/tips-and-tricks.rst
