name: pick-files
base: core22
adopt-info: pick-files

summary: A script that picks a random selection of files
description: |
  A script that copies a random selection of files from a set of folders to a
  single destination folder.

grade: stable
confinement: strict

apps:
  pick-files:
    command: usr/bin/pick-files

parts:
  pick-files:
    plugin: dump
    source: .
    build-snaps:
      - go
    override-build: |
      set -e -u -x
      VERSION=$(git describe --tags)
      craftctl set version=${VERSION}
      go build -ldflags "-X main.Version=${VERSION}" -o pick-files ./...
      install --mode 0755 -D pick-files ${CRAFT_PART_INSTALL}/usr/bin/pick-files
