---

name: Go package build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build
        run: make
      - name: Simple test
        run: |
          set -e -u -x
          ./pick-files --version
          ./pick-files --number 10 --destination output-1 --folder artifacts/a/a
          ./pick-files --number 10 --destination output-2 --folder artifacts/a/a
          ./pick-files --number 10 --destination output-3 --folder artifacts/a/a
          ./pick-files --print-database-statistics

      - name: Test
        run: make test

      - name: Coverage
        run: make coverage
