---

name: Go package build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
        matrix:
            go-version: ["1.16", "1.17", "1.18", "1.19", "1.20"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: |
          go build -ldflags "-X main.Version=$(git describe --tags)" -v -o pick-files ./...

      - name: Simple test
        run: |
          set -e -u -x
          ./pick-files --version
          ./pick-files --number 10 --destination output-1 --folder artifacts/a/a
          ./pick-files --number 10 --destination output-2 --folder artifacts/a/a
          ./pick-files --number 10 --destination output-3 --folder artifacts/a/a

      - name: Test
        run: go test -v ./...
