---

name: Snap package build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: snapcore/action-build@v1
        id: snapcraft
        with:
          snapcraft-args: --verbosity=debug

      - run: |
          sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
          pick-files --help

      - uses: actions/upload-artifact@v3
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: logs
          path: '/home/runner/.local/state/snapcraft/log/snapcraft-*.log'
